version: '3'
services:
    mongodb:
      image: mongo
      ports:
        - "27017:27017"

    mongo-seed:
      image: bilges/reporting_db
      links:
       - mongodb

    api:
      image: bilges/reporting_db_api
      ports:
        - "5000:5000"
      depends_on:
        - mongo-seed

    filedeploy:
      image: bilges/file_deploy:93
      volumes:
        - dependencyF:/mnt

    ClinicalReportR: 
      image: bilges/reporting_app:93
      volumes:
        - dependencyF:/data
        - ./ReportingApplication/inout:/inout
      # entrypoint: /bin/bash
      network_mode: "host"
      depends_on:
        - api
        - mongo-seed
        - filedeploy
      # stdin_open: true
      # tty: true
volumes:
  dependencyF:
  